# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/payment/v1/payment.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eproto/payment/v1/payment.proto\x12\x10proto.payment.v1\"\x86\x01\n\x07Payment\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n\x06\x61mount\x18\x02 \x01(\x01R\x06\x61mount\x12\x1a\n\x08\x63urrency\x18\x03 \x01(\tR\x08\x63urrency\x12\x37\n\x06status\x18\x04 \x01(\x0e\x32\x1f.proto.payment.v1.PaymentStatusR\x06status\"g\n\x18\x43reateTransactionRequest\x12\x16\n\x06\x61mount\x18\x01 \x01(\x01R\x06\x61mount\x12\x1a\n\x08\x63urrency\x18\x02 \x01(\tR\x08\x63urrency\x12\x17\n\x07user_id\x18\x03 \x01(\tR\x06userId\"P\n\x19\x43reateTransactionResponse\x12\x33\n\x07payment\x18\x01 \x01(\x0b\x32\x19.proto.payment.v1.PaymentR\x07payment*\x84\x01\n\rPaymentStatus\x12\x1e\n\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x1c\n\x18PAYMENT_STATUS_COMPLETED\x10\x02\x12\x19\n\x15PAYMENT_STATUS_FAILED\x10\x03\x32~\n\x0ePaymentService\x12l\n\x11\x43reateTransaction\x12*.proto.payment.v1.CreateTransactionRequest\x1a+.proto.payment.v1.CreateTransactionResponseBAZ?github.com/rohanchauhan02/proto-def/gen/go/payment/v1;paymentv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.payment.v1.payment_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z?github.com/rohanchauhan02/proto-def/gen/go/payment/v1;paymentv1'
  _PAYMENTSTATUS._serialized_start=377
  _PAYMENTSTATUS._serialized_end=509
  _PAYMENT._serialized_start=53
  _PAYMENT._serialized_end=187
  _CREATETRANSACTIONREQUEST._serialized_start=189
  _CREATETRANSACTIONREQUEST._serialized_end=292
  _CREATETRANSACTIONRESPONSE._serialized_start=294
  _CREATETRANSACTIONRESPONSE._serialized_end=374
  _PAYMENTSERVICE._serialized_start=511
  _PAYMENTSERVICE._serialized_end=637
# @@protoc_insertion_point(module_scope)
